{"name": "test_002", "status": "passed", "steps": [{"name": "第二个测试步骤", "status": "passed", "attachments": [{"name": "第二个标题", "source": "df2f2134-a6fd-4461-9f33-00b6892e03cf-attachment.attach"}], "start": 1626768418785, "stop": 1626768418785}], "start": 1626768418785, "stop": 1626768418785, "uuid": "ab1d0cd5-04dd-4e79-8280-260e78aade38", "historyId": "ca78ca8c3135aac09d28f5a2246d6a94", "testCaseId": "490888ffce351d59333cc21bb0b9645d", "fullName": "scripts.test001.Test01#test_002", "labels": [{"name": "severity", "value": "minor"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test001"}, {"name": "subSuite", "value": "Test01"}, {"name": "host", "value": "DESKTOP-GPMDE76"}, {"name": "thread", "value": "82472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test001"}], "links": [{"type": "issue", "url": "140", "name": "Pytest-flaky test retries shows like test steps"}]}